#!/usr/bin/sh
#
# This is executed by systemd as defined in ipfsd.service
#
# This will send an arbitrary message to the journal queriable with 'journalctl
# -t <identifier>' in this case 'journalctl -t ipfsd.service', where the
# identifier is defined in /etc/sysconfig/ipfsd as JOURNAL_IDENTIFIER
#
# Do not edit this file. These values, which are unlikely to need to be changed, are
# instead configured in:
# /etc/sysconfig/ipfsd and /usr/lib/systemd/ipfsd.service
#

# STAGE and DATE_LOG aren't really used currently.
STAGE=$1
DATE_LOG=$(/usr/bin/date --utc +"%b %d %T UTC")

JOURNAL_IDENTIFIER=$2
MESSAGE=$3


start() {
  if [[ ! -z $JOURNAL_IDENTIFIER && ! -z $MESSAGE ]] ; then
    /usr/bin/echo "$MESSAGE" | systemd-cat -t $JOURNAL_IDENTIFIER
  fi
}


stop() {
  if [[ ! -z $JOURNAL_IDENTIFIER && ! -z $MESSAGE ]] ; then
    /usr/bin/echo "$MESSAGE" | systemd-cat -t $JOURNAL_IDENTIFIER
  fi
}


case "$STAGE" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  *) exit 1
esac

